Authentication
OmAsana/go-yapraktikum-final pull request #3
Opened 2022-04-25 09:56 UTC by OmAsana

2022-04-29 13:46 UTC, ASPecherkin requested changes
Все нравится, но оставил пару комментариев , которые возникли

2022-04-29 13:46 UTC, ASPecherkin commented on pkg/bonussystem/bonussystem.go
> +	inShutdown bool
а зто что это поле будет отвечать? 
не нашёл дальше по коду

2022-04-29 13:46 UTC, ASPecherkin commented on pkg/bonussystem/bonussystem.go
> +		case <-time.After(1 * time.Second):
тут лучше это вынести в параметры bonus system и конфигурировать снаружи 

Так будет удобнее, если в будущем появится новые требования работы с системой 

и оставить 1 time.Second как default значение

2022-05-01 08:01 UTC, OmAsana commented on pkg/bonussystem/bonussystem.go
> +	inShutdown bool
Осталось от первой версии. Не заметил, что осталось.

2022-05-01 08:01 UTC, OmAsana commented on pkg/bonussystem/bonussystem.go
> +		case <-time.After(1 * time.Second):
Вынес в опции.

2022-05-02 07:28 UTC, ASPecherkin approved these changes
Принимаю, всё хорошо

2022-05-03 15:29 UTC, merged